### ISSUE TITLE
Progress bar: too many per file

### ISSUE THREAD

**Issue by cinquecento** [vitalif/grive2#104] opened 2016-09-30 07:11 UTC
vitalif/grive2
```
$ grive --progress-bar
Reading local directories
Reading remote server file list
Synchronizing files
sync "./Test/1B.file" doesn't exist in server, uploading
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
  [100%] [==================================================>] 0.231 KB/0.231 KB
Finished!

$ grive --progress-bar
Reading local directories
Reading remote server file list
Synchronizing files
sync "./Test/1KB.file" doesn't exist in server, uploading
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
  [100%] [==================================================>] 1.234 KB/1.234 KB
Finished!

$ grive --progress-bar
Reading local directories
Reading remote server file list
Synchronizing files
sync "./Test/1MB.file" doesn't exist in server, uploading
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
  [100%] [==================================================>] 1.000 MB/1.000 MB
Finished!

$ grive --progress-bar
Reading local directories
Reading remote server file list
Synchronizing files
sync "./Test/10MB.file" doesn't exist in server, uploading
  [ 10%] [====>                                              ] 1008.000 KB/10.000 M  [ 10%] [====>                                              ] 1008.000 KB/10.000 M  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
  [100%] [==================================================>] 10.000 MB/10.000 MB
Finished!
```
svartkanin/grive2
```
$ grive --progress-bar
Reading local directories
Reading remote server file list
3 total changes
Synchronizing files
sync "./Test/1B.file" doesn't exist in server, uploading
  [100%] [==================================================>] 0.00KB/0.00KB
  [100%] [==================================================>] 2.00KB/2.00KB
Finished!

$ grive --progress-bar
Reading local directories
Reading remote server file list
3 total changes
Synchronizing files
sync "./Test/1KB.file" doesn't exist in server, uploading
  [100%] [==================================================>] 1.00KB/1.00KB
  [100%] [==================================================>] 2.00KB/2.00KB
Finished!

$ grive --progress-bar
Reading local directories
Reading remote server file list
3 total changes
Synchronizing files
sync "./Test/1MB.file" doesn't exist in server, uploading
  [100%] [==================================================>] 1024.00KB/1024.00KB
Finished!

$ grive --progress-bar
Reading local directories
Reading remote server file list
3 total changes
Synchronizing files
sync "./Test/10MB.file" doesn't exist in server, uploading
  [100%] [==================================================>] 10.00MB/10.00MB
Finished!
```

**Comment by vitalif** [comment] 2016-09-30 07:56
@svartkanin's original implementation doesn't differ from merged one for uploaded files, it also just uses curl progress callback. Anyway, I think printing progress several times per second is ok, it shouldn't affect terminal performance.

**Comment by vitalif** [comment] 2016-09-30 09:23
Ah ok I've understood what you mean, you mean the problem is that multiple progressbar lines are printed per file... ok I'll fix it shortly

**Closed** 2016-09-30 09:33 UTC

**Comment by cinquecento** [comment] 2016-09-30 15:32
See https://github.com/vitalif/grive2/issues/105
