### ISSUE TITLE
sync from two locations

### ISSUE THREAD

**Issue by mkauzlar** [vitalif/grive2#6] opened 2015-05-22 05:09 UTC
Hello,

I have two locations where I use grive, at home and in the office (with two separate PCs)

Yesterday in the office I deleted a bunch of files locally and run grive to sync to google drive. All ok there, the files were removed in the drive too.
Today I run grive on my pc at home and it says that some files are missing on the google drive (the ones I deleted yesterday) and attempts to upload them.

What I would expect is that it removes the files locally in the home pc.

Regards

**Comment by h4kuna** [comment] 2015-05-29 16:33
I have same problem.

**Comment by vitalif** [comment] 2015-10-08 09:53
I've tried to reproduce this bug yesterday and found 2 issues:

(A) Grive2 was NEVER deleting local files when used with -p option because .grive_state was saved in current working directory instead of synced root - it was thinking the last sync time is 0 and so all local files are new and should be uploaded to the server. .trash was also saved in current working directory instead of synced root. This is now fixed in master.

(B) Another issue is that grive2 does not delete local files deleted at the server side if they were downloaded from the server. I.e. the scenario is:

1. create directory test1, copy some files into it
2. run `grive -p test1 -a` to sync these files to server
3. create directory test2
4. run `grive -p test2 -a` to download files that were just created at step 2
5. delete some files in test1
6. run `grive -p test1` to sync this deletion to server
7. run `grive -p test2` to sync server-side deletion to local dir
--> BANG! files will be recreated on the server instead of being deleted in test2.

At the same time, if you swap test1 and test2 in steps 5-7 (i.e. delete file in test2, sync it to server, then sync test1 with grive), the files will be deleted!

This is because Grive2 decides whether the file is deleted at the server side or created locally by comparing file ctime (inode change time) with the last sync time. But the last sync time is not just system time at the end of the last sync, it's the maximum server-side file change time seen during the sync process. And obviously it's always less than ctime when the file is downloaded from the server, that's why grive2 thinks all downloaded files are "locally new".

I think the proper fix is to compare inode ctime with the last local sync time instead of the last server sync time. And because the server-side sync time is also used to compare server-side change times, grive should track both times...

I'll fix it in master shortly.

**Closed** 2015-10-08 10:29 UTC
