### ISSUE TITLE
Synchronization takes ages

### ISSUE THREAD

**Issue by oOZeVsOo** [vitalif/grive2#52] opened 2015-12-29 12:22 UTC
On my 1 To (85% full) drive, it takes 2 to 3 hours of computing before sending any actual data. even if I have only added a single file.

I know that since grive is not running in background, it can't be aware of file modifications (unlike the windows official client) so I guess there is no simple answer to that problem.

IMHO, a solution could be a "fast" mode, that does not check for file modifications but only for files added or removed. Since no checksum would be computed in this mode it would be a lot faster.
It could be used for fast upload, between two comprehensive "regular" scans.

Another solution could be a "simple" mode, using a faster way to compare files. For exemple by only checking file size, date and name. Or by using a faster checksum algorithm.

Thank you very much.

**Comment by vitalif** [comment] 2015-12-29 12:47
Good way to fix this is adding a local git-like index based on inode change times & checksums...

**Comment by oOZeVsOo** [comment] 2015-12-29 13:08
It's way better indeed, but it's a huge improvement.

**Comment by vitalif** [comment] 2016-01-02 20:23
I've committed "index" support to master today, please test :-)

**Comment by oOZeVsOo** [comment] 2016-01-05 19:48
Thank you very much !
I've been testing it for a few days now and it was working flawlessly (15 minutes for checking my 800 GB instead of 2 hours !).

But since this morning, every time I add something in a directory (new pictures, for example), I get a "sync "XXX.JPG" deleted in remote. deleting local" message and all my new files are gone.
The worse is that I can find nothing in my local trash or in the google drive trash.

Do you have an idea about what's happening ?

Thank you very much.

**Comment by vitalif** [comment] 2016-01-05 22:12
Grive really never deletes anything, there never was a single call to unlink() in its code. It puts deleted files in the .trash subdirectory of the synced root folder... also older versions of grive had a bug which made it put the .trash subdirectory in the current working directory from which grive was called instead of the synced root. So check these two locations, your new files should be there.

The bug you've described looks exactly like what it have been BEFORE the local index implementation - it was only yesterday that I had to recompress and reupload my backups for last ~2 months because grive always deleted new files instead of uploading them to server :) can it be so that you're invoking an older grive executable which has this bug?..

**Comment by vitalif** [comment] 2016-01-05 22:22
If you're 100% sure you're running the latest version from the master branch (note I've rebased it several times so make sure you're not on some older variant)... then please tell me if the bug reproduces with files added to the root directory or just to new files added to subdirs. There are only 2 places from which the `remote_deleted` can originate: either the local index (.grive_state) should have the new file with the same ctime as in filesystem, or the state may be inherited from the parent directory of the file...

**Comment by vitalif** [comment] 2016-01-05 22:51
Ok, I've found that bug. It reproduced only with files put in subdirs of level >= 2 (i.e. at least sub-subdirs) of drive root due to that piece of code with state inheritance left from the old grive code. Try the master branch for the fix.

**Closed by vitalif** 2016-01-05 22:51 UTC
