### ISSUE TITLE
 Google Account sign-in is temporarily disabled for this application

### ISSUE THREAD

**Issue by marques576** [vitalif/grive2#324] opened 2020-09-20 10:14 UTC
When i click the link i get the message in the title

![image](https://user-images.githubusercontent.com/23244686/93708961-78180c80-fb32-11ea-874d-845c661f804f.png)

**Comment by zetneteork** [comment] 2020-09-24 16:23
I am having the same issue with using a link from the command:
```bash
grive2 -a
```

Do you know how to prepare **ID** and **SECRET**? That would be maybe a possible way how to auth the app.
```
  -i [ --id ] arg             Authentication ID
  -e [ --secret ] arg         Authentication secret
```

**Comment by proski** [comment] 2020-09-24 23:53
Duplicate of #287.

**Closed** 2021-05-27 14:16 UTC
