### ISSUE TITLE
const: Assertion `m_ctx.size() == 1U' failed.

### ISSUE THREAD

**Issue by df1paw** [vitalif/grive2#26] opened 2015-09-04 23:14 UTC
Grive -a fails with the following error:

andreas@notebook:~/src/grive2/build/grive$ ./grive -a
-----------------------
Please go to this URL and get an authentication code:

Link removed
-----------------------
Please input the authentication code here: 
code removed
grive: /home/andreas/src/grive2/libgrive/src/json/ValBuilder.cc:133: gr::Val gr::ValBuilder::Result() const: Assertion `m_ctx.size() == 1U' failed.
Abgebrochen (Speicherabzug geschrieben)

**Comment by vitalif** [comment] 2015-09-26 19:01
Does it reproduce every time?

**Comment by efuquen** [comment] 2015-09-29 02:51
I can confirm this is repeatedly happening for me, can't use grive2.  Initially thought it might be related to me having 2 factor authentication enabled, but I disabled it and still got the same error:

grive: /home/efuquen/Code/oss/grive2/libgrive/src/json/ValBuilder.cc:133: gr::Val gr::ValBuilder::Result() const: Assertion `m_ctx.size() == 1U' failed.
Aborted (core dumped)

**Comment by vitalif** [comment] 2015-09-30 12:28
I've just reimplemented HTTP response logging in grive, so please check `grive -a --log-http http` with the latest master version. httpXXX.txt file will be created with the full communication transcript.
In fact it seems I've also reproduced your issue by repeating auth request many times, and now Google always says to me:
```{
  "error" : "invalid_grant",
  "error_description" : "Code was already redeemed."
}```
Don't yet know how to fix it though O_o it repeats every time for me now.
+ also the "assertion failed" tells up that ValBuilder failed to parse JSON response. This is also a bug which I'll fix...

**Comment by vitalif** [comment] 2015-09-30 12:52
Oh, that's not ValBuilder, it's just OAuth2 not handling error responses. Fixed in master, now it will print "Failed to obtain auth token".

**Comment by vitalif** [comment] 2015-10-07 19:59
The problem was that google for some occasion was giving me the same oauth2 code every time. Of course it was "already redeemed". So I believe the bug is fixed, please reopen it if you still have the problem.

**Closed by vitalif** 2015-10-07 19:59 UTC
