### ISSUE TITLE
Progress bar: slow update of the value of data transferred

### ISSUE THREAD

**Issue by cinquecento** [vitalif/grive2#103] opened 2016-09-29 21:48 UTC
vitalif/grive2
Implement progressbar

Update of the value of data transferred is rather slow,
gives the impression of a stalled network traffic
```
$ grive --progress-bar
Reading local directories
Reading remote server file list
Synchronizing files
sync "./Test/1.1GB.file" doesn't exist in server, uploading
  [  0%] [>                                               ] 0.000 KB/1.098 GB      00:00s
  [  0%] [>                                               ] 576.000 KB/1.098 GB    00:07s
  [  0%] [>                                               ] 1.688 MB/1.098 GB      00:27s
  [  0%] [>                                               ] 2.812 MB/1.098 GB^C    00:50s
```
svartkanin/grive2
Updated Progress Bar

Update of the value of data transferred is agile
```
$ grive --progress-bar
Reading local directories
Reading remote server file list
3 total changes
Synchronizing files
sync "./Test/1.1GB.file" doesn't exist in server, uploading
  [  0%] [>                                               ] 0.00KB/1.10GB
  [  0%] [>                                               ] 31.00KB/1.10GB
  [  0%] [>                                               ] 32.00KB/1.10GB
  [  0%] [>                                               ] 48.00KB/1.10GB
  [  0%] [>                                               ] 64.00KB/1.10GB
  [  0%] [>                                               ] 80.00KB/1.10GB
  [  0%] [>                                               ] 96.00KB/1.10GB
  [  0%] [>                                               ] 112.00KB/1.10GB
  [  0%] [>                                               ] 112.00KB/1.10GB
  [  0%] [>                                               ] 128.00KB/1.10GB
  [  0%] [>                                               ] 144.00KB/1.10GB
  [  0%] [>                                               ] 160.00KB/1.10GB
  [  0%] [>                                               ] 176.00KB/1.10GB
  [  0%] [>                                               ] 192.00KB/1.10GB
  [  0%] [>                                               ] 208.00KB/1.10GB
  [  0%] [>                                               ] 224.00KB/1.10GB
  [  0%] [>                                               ] 240.00KB/1.10GB
  [  0%] [>                                               ] 256.00KB/1.10GB
  [  0%] [>                                               ] 272.00KB/1.10GB
  [  0%] [>                                               ] 288.00KB/1.10GB
  [  0%] [>                                               ] 304.00KB/1.10GB
  [  0%] [>                                               ] 320.00KB/1.10GB
  [  0%] [>                                               ] 352.00KB/1.10GB
  [  0%] [>                                               ] 368.00KB/1.10GB
  [  0%] [>                                               ] 384.00KB/1.10GB
  [  0%] [>                                               ] 400.00KB/1.10GB
  [  0%] [>                                               ] 416.00KB/1.10GB
  [  0%] [>                                               ] 432.00KB/1.10GB
  [  0%] [>                                               ] 448.00KB/1.10GB
  [  0%] [>                                               ] 464.00KB/1.10GB
  [  0%] [>                                               ] 496.00KB/1.10GB
  [  0%] [>                                               ] 512.00KB/1.10GB
  [  0%] [>                                               ] 528.00KB/1.10GB
  [  0%] [>                                               ] 544.00KB/1.10GB
  [  0%] [>                                               ] 560.00KB/1.10GB
  [  0%] [>                                               ] 576.00KB/1.10GB
  [  0%] [>                                               ] 592.00KB/1.10GB
  [  0%] [>                                               ] 608.00KB/1.10GB
  [  0%] [>                                               ] 624.00KB/1.10GB
  [  0%] [>                                               ] 640.00KB/1.10GB
  [  0%] [>                                               ] 656.00KB/1.10GB
  [  0%] [>                                               ] 672.00KB/1.10GB
  [  0%] [>                                               ] 688.00KB/1.10GB
  [  0%] [>                                               ] 704.00KB/1.10GB
  [  0%] [>                                               ] 720.00KB/1.10GB
  [  0%] [>                                               ] 736.00KB/1.10GB
  [  0%] [>                                               ] 752.00KB/1.10GB
  [  0%] [>                                               ] 768.00KB/1.10GB
  [  0%] [>                                               ] 784.00KB/1.10GB
  [  0%] [>                                               ] 800.00KB/1.10GB
  [  0%] [>                                               ] 816.00KB/1.10GB
  [  0%] [>                                               ] 832.00KB/1.10GB
  [  0%] [>                                               ] 848.00KB/1.10GB
  [  0%] [>                                               ] 864.00KB/1.10GB
  [  0%] [>                                               ] 880.00KB/1.10GB
  [  0%] [>                                               ] 912.00KB/1.10GB
  [  0%] [>                                               ] 928.00KB/1.10GB
  [  0%] [>                                               ] 944.00KB/1.10GB
  [  0%] [>                                               ] 960.00KB/1.10GB
  [  0%] [>                                               ] 976.00KB/1.10GB
  [  0%] [>                                               ] 992.00KB/1.10GB
  [  0%] [>                                               ] 1008.00KB/1.10GB
  [  0%] [>                                               ] 1024.00KB/1.10GB
  [  0%] [>                                               ] 1.05MB/1.10GB
  [  0%] [>                                               ] 1.06MB/1.10GB
  [  0%] [>                                               ] 1.08MB/1.10GB
  [  0%] [>                                               ] 1.09MB/1.10GB
  [  0%] [>                                               ] 1.11MB/1.10GB
  [  0%] [>                                               ] 1.16MB/1.10GB
  [  0%] [>                                               ] 1.17MB/1.10GB
  [  0%] [>                                               ] 1.19MB/1.10GB
  [  0%] [>                                               ] 1.20MB/1.10GB
  [  0%] [>                                               ] 1.22MB/1.10GB
  [  0%] [>                                               ] 1.23MB/1.10GB
  [  0%] [>                                               ] 1.25MB/1.10GB
  [  0%] [>                                               ] 1.27MB/1.10GB
  [  0%] [>                                               ] 1.28MB/1.10GB
  [  0%] [>                                               ] 1.30MB/1.10GB
  [  0%] [>                                               ] 1.31MB/1.10GB
  [  0%] [>                                               ] 1.33MB/1.10GB
  [  0%] [>                                               ] 1.34MB/1.10GB
  [  0%] [>                                               ] 1.36MB/1.10GB
  [  0%] [>                                               ] 1.38MB/1.10GB
  [  0%] [>                                               ] 1.39MB/1.10GB
  [  0%] [>                                               ] 1.41MB/1.10GB
  [  0%] [>                                               ] 1.42MB/1.10GB
  [  0%] [>                                               ] 1.44MB/1.10GB
  [  0%] [>                                               ] 1.45MB/1.10GB
  [  0%] [>                                               ] 1.47MB/1.10GB
  [  0%] [>                                               ] 1.48MB/1.10GB
  [  0%] [>                                               ] 1.50MB/1.10GB
  [  0%] [>                                               ] 1.52MB/1.10GB
  [  0%] [>                                               ] 1.53MB/1.10GB
  [  0%] [>                                               ] 1.55MB/1.10GB
  [  0%] [>                                               ] 1.56MB/1.10GB
  [  0%] [>                                               ] 1.58MB/1.10GB
  [  0%] [>                                               ] 1.59MB/1.10GB
  [  0%] [>                                               ] 1.61MB/1.10GB
  [  0%] [>                                               ] 1.62MB/1.10GB
  [  0%] [>                                               ] 1.64MB/1.10GB
  [  0%] [>                                               ] 1.66MB/1.10GB
  [  0%] [>                                               ] 1.67MB/1.10GB
  [  0%] [>                                               ] 1.69MB/1.10GB
  [  0%] [>                                               ] 1.70MB/1.10GB
  [  0%] [>                                               ] 1.72MB/1.10GB
  [  0%] [>                                               ] 1.73MB/1.10GB
  [  0%] [>                                               ] 1.75MB/1.10GB
  [  0%] [>                                               ] 1.77MB/1.10GB
  [  0%] [>                                               ] 1.78MB/1.10GB
  [  0%] [>                                               ] 1.80MB/1.10GB
  [  0%] [>                                               ] 1.81MB/1.10GB
  [  0%] [>                                               ] 1.83MB/1.10GB
  [  0%] [>                                               ] 1.84MB/1.10GB
  [  0%] [>                                               ] 1.86MB/1.10GB
  [  0%] [>                                               ] 1.88MB/1.10GB
  [  0%] [>                                               ] 1.89MB/1.10GB
  [  0%] [>                                               ] 1.91MB/1.10GB
  [  0%] [>                                               ] 1.92MB/1.10GB
  [  0%] [>                                               ] 1.94MB/1.10GB
  [  0%] [>                                               ] 1.95MB/1.10GB
  [  0%] [>                                               ] 1.97MB/1.10GB
  [  0%] [>                                               ] 1.98MB/1.10GB
  [  0%] [>                                               ] 2.00MB/1.10GB
  [  0%] [>                                               ] 2.02MB/1.10GB
  [  0%] [>                                               ] 2.03MB/1.10GB
  [  0%] [>                                               ] 2.05MB/1.10GB
  [  0%] [>                                               ] 2.06MB/1.10GB
^C
```

**Comment by vitalif** [comment] 2016-09-29 22:14
This was intended, it thought it will be good to print progressbar every 1/1000 of file transferred... ok, I'm removing it.

**Closed** 2016-09-29 22:15 UTC

**Comment by cinquecento** [comment] 2016-09-30 07:11
See https://github.com/vitalif/grive2/issues/104
