### ISSUE TITLE
Fedora 31 http  error

### ISSUE THREAD

**Issue by makgab** [vitalif/grive2#291] opened 2019-12-02 19:30 UTC
Hi!
Today I got this error with grive2:
`# grive
Failed to refresh auth token: HTTP 401, body:
exception: /builddir/build/BUILD/grive2-0.5.1/libgrive/src/protocol/OAuth2.cc(111): Throw in function void gr::OAuth2::Refresh()
Dynamic exception type: boost::wrapexcept<gr::OAuth2::AuthFailed>`

(In my G account, the grive has access.)
5.3.13-300.fc31.x86_64
grive version 0.5.1 Nov 23 2019 00:00:00
grive2-0.5.1-2.fc31.x86_64

**Comment by makgab** [comment] 2019-12-02 19:35
the grive version 0.5.1-dev Jul 25 2019 00:00:00 (downgraded) is working now.

**Comment by proski** [comment] 2019-12-04 19:02
Duplicate of #287 (which has a workaround)

**Closed** 2020-06-10 05:58 UTC
